#!/usr/bin/env bash

PKGS_DEBIAN="apt-transport-https htop pv software-properties-common tmux wget zsh"
PKGS_UBUNTU="apt-transport-https htop pv tmux wget zsh"

wget -O /etc/skel/.zshrc https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc

OS="`ls /etc/*release`"
case "$OS" in
  *rch*)
    pacman -Syyu ansible base-devel fail2ban git docker docker-compose nginx nodejs reflector vim zsh
    ;;
  *ebian*)
    apt update && apt install "${PKGS_DEBIAN}"
    echo "deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main" >>  /etc/apt/sources.list
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
    apt update && apt install ansible && apt autoremove -yq
    ;;
  *buntu*)
    apt update && apt install "${PKGS_UBUNTU}"
    apt-add-repository --yes --update ppa:ansible/ansible
    apt update && apt install ansible && apt autoremove -yq
    ;; 
  *) break ;;

useradd -u 3333 -s /bin/bash -c "ansible" -m ansible
echo "ansible ALL=NOPASSWD: ALL" >> /etc/sudoers.d/ansible
chmod 440 /etc/sudoers.d/ansible
chmod 750 /home/ansible
mkdir /home/ansible/.ssh/
chown ansible:root /home/ansible/.ssh/
chmod 750 /home/ansible/.ssh/
touch /home/ansible/.ssh/authorized_keys
